env:
  browser: true
  node: true
  es6: true
extends: [
    "eslint:recommended",
    "plugin:react/recommended"
  ]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  "semi": ["error", "always"],
  "quotes": ["error", "double"],
  "no-undef": "off",
  "react/react-in-jsx-scope": "off",
  "react/jsx-no-undef": "off",
  "no-unused-vars": "off"
}
